[[test_servers]]
name = "vm"
host = "192.168.2.232"
user = "vagrant"
key = "environments/cms/ssh_key/test_key"

[contest]
name = "toi-primary-2023-test"
description = "TOI Primary 2023 test"
token_mode = "infinite"

[[contest.users]]
username = "u1"
password = "p1"

[contest-config]
languages = ["C11 / gcc", "C++14 / g++", "Java / JDK", "Python 3 / CPython"]

[contest-config.mapping]
"C11 / gcc" = [".c"]
"C++14 / g++" = [".cpp", ".cc", ".cxx", ".c++", ".C"]
"Java / JDK" = [".java"]
"Python 3 / CPython" = [".py"]

[task_template]
infile = ""
outfile = ""
task_type = "Batch"
score_mode = "max_subtask" # 2017~
token_mode = "infinite"
score_type = "GroupMin"
score_type_parameters = ""
time_limit = 15
memory_limit = 1024

[[tasks]]
name = "house"
title = "house"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]

[[tasks]]
name = "storm"
title = "storm"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]
  4 = ["1", "2"]
  6 = ["1", "2", "3", "4", "5"]

[[tasks]]
name = "game"
title = "game"
time_limit = 1.0
  [tasks.inclusive_tests]
  4 = ["1", "2", "3"]

[[tasks]]
name = "molecule"
title = "molecule"
time_limit = 0.2
  [tasks.inclusive_tests]
  2 = ["1"]
  4 = ["1", "2", "3"]

[[tasks]]
name = "road"
title = "road"
time_limit = 2.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]
  4 = ["1", "2", "3"]
